config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources:books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title,presence:true
  validates :body,presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book =Book.new
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice]="Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice]="Book was successfully destroyed."
    redirect_to '/books'
  end
  
  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1 class="head">Editing Book</h1>

<div class="error">
    <% if @book.errors.any? %>
     <div class="error-box">
      <p class="error-title">
        <b><%= pluralize(@book.errors.count,"error")%> prohibited this book from being saved:</b>
      </p>
      <ul class="error-message">
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
     </div>
    <% end %>
    </div>

<%= form_with model:@book do |f| %>

<p>Title</p>
<div class="form">
<%= f.text_field :title %>
</div>
<p>Body</p>
<div class="form">
<b><%= f.text_area :body %></b>
</div>
<%= f.submit ' Update Book ' %>
<% end %>
<div class="btn">
<%= link_to "show","/books/#{@book.id}" %> | <%= link_to "Back","/books" %>
</div>

app/views/books/index.html.erb
<body>
  <div class="flash">
  <%= flash[:notice] %>
  </div>
  
  <h1 class="head">Books</h1>
  
  <table>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show","/books/#{book.id}" %> </td>
      <td><%= link_to "Edit","/books/#{book.id}/edit" %> </td>
      <td><%= link_to "Destroy",book_path(book.id),method: :delete,"data-confirm"=>"Are you sure?" %> </td>
    </tr>
    <% end %>
  </table>
  
  <div class="post">
    <h2 class="post-head">New books</h2>
    
    <%= form_with model: @book,url:'/books',method: :post do |f| %>
    
    <div class="error">
    <% if @book.errors.any? %>
     <div class="error-box">
      <p class="error-title">
        <b><%= pluralize(@book.errors.count,"error") %> prohibited this book from being saved:</b>
      </p>
      <ul class="error-message">
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
     </div>
    <% end %>
    
      <p>Title</p>
      <div class="form">
      <%= f.text_field :title %>
      </div>
      <p>Body</p>
      <div class="form">
      <%= f.text_area :body %>
      </div>
      <%= f.submit ' Create Book ' %>
    <% end %>
    </div>
  </div>

</body>

app/views/books/show.html.erb
<div class="flash">
  <%= flash[:notice] %>
</div>
<body>
<p class="show-content"><b>Title: </b><%= @book.title %> </p>

<p class="show-content"><b>Body: </b><%= @book.body %></p>


<%= link_to "Edit","/books/#{@book.id}/edit" %> | <%= link_to "Back","/books" %>
</body>

app/views/homes/top.html.erb
<body>
  <h1 class="head">ようこそ Bookers へ！</h1>
  
  <p class="top-content"><b>Bookers</b> では、さまざまな書籍に関するあなたの意見や<br></p>
  <p class="top-content">印象を共有し交換することができます</p>
  <div class="link">
  <%= link_to "srart", books_path %>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>